version: '3.9'

services:

  postgres-db:
    image: postgres:15
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: liverpool_orders
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - liverpool-net

  mongo-db:
    image: mongo:6
    container_name: mongo-db
    restart: always
    environment:
      MONGO_INITDB_DATABASE: liverpool_orders
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
    networks:
      - liverpool-net

volumes:
  pgdata:
  mongodata:

networks:
  liverpool-net:
    driver: bridge
